id = "github-classic"
name = "Github Classic"
schema_version = 1
version = "0.0.2"
authors = ["Nguyen Dang Vinh <meocoder@gmail.com>"]
description = "The classic GitHub Light and GitHub Dark themes for Zed"
repository = "https://github.com/meocoder31099/Github-Classic-Theme-Zed"
